[2025-08-04T12:45:23.137+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-04T12:45:23.164+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stress_detection_complete_pipeline.retrieve_data_from_drive manual__2025-08-04T05:45:20.659290+00:00 [queued]>
[2025-08-04T12:45:23.171+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stress_detection_complete_pipeline.retrieve_data_from_drive manual__2025-08-04T05:45:20.659290+00:00 [queued]>
[2025-08-04T12:45:23.172+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-08-04T12:45:23.187+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): retrieve_data_from_drive> on 2025-08-04 05:45:20.659290+00:00
[2025-08-04T12:45:23.194+0700] {standard_task_runner.py:63} INFO - Started process 225 to run task
[2025-08-04T12:45:23.197+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stress_detection_complete_pipeline', 'retrieve_data_from_drive', 'manual__2025-08-04T05:45:20.659290+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/stress_detection_complete_pipeline.py', '--cfg-path', '/tmp/tmpyq76z25t']
[2025-08-04T12:45:23.200+0700] {standard_task_runner.py:91} INFO - Job 3: Subtask retrieve_data_from_drive
[2025-08-04T12:45:23.301+0700] {task_command.py:426} INFO - Running <TaskInstance: stress_detection_complete_pipeline.retrieve_data_from_drive manual__2025-08-04T05:45:20.659290+00:00 [running]> on host 7aea066467c1
[2025-08-04T12:45:23.391+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='stress_detection_complete_pipeline' AIRFLOW_CTX_TASK_ID='retrieve_data_from_drive' AIRFLOW_CTX_EXECUTION_DATE='2025-08-04T05:45:20.659290+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-04T05:45:20.659290+00:00'
[2025-08-04T12:45:23.393+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-04T12:45:23.410+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-04T12:45:23.411+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stress_detection_complete_pipeline.py", line 21, in retrieve_data_from_drive
    from src.preprocess.fetch_and_store import retrieve_data
ModuleNotFoundError: No module named 'src'
[2025-08-04T12:45:23.423+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stress_detection_complete_pipeline, task_id=retrieve_data_from_drive, run_id=manual__2025-08-04T05:45:20.659290+00:00, execution_date=20250804T054520, start_date=20250804T054523, end_date=20250804T054523
[2025-08-04T12:45:23.442+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task retrieve_data_from_drive (No module named 'src'; 225)
[2025-08-04T12:45:23.452+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-04T12:45:23.473+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T12:45:23.476+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
